### PR TITLE
Update README, add support for NATS in nix.shell, update duck art

### PR DESCRIPTION
**Pull request by cornbread5**
Added info on how to install and setup NATS and send and receive messages.

### CODE REVIEW

**Review by bmorphism — CHANGES_REQUESTED** [review]
Needs to be compatible with nix just like every other package, contribute to upstream if necessary. Reproducibility is more important than shipping non-integrated dependencies.

https://blog.replit.com/super-colliding-nix-stores

**Comment by cornbread5** [comment]
I've updated the nix.shell to include the required packages. Should be ready to merge after review 👍

**Comment by bmorphism** [comment]
NATS log:
```
[nix-shell:~/plurigrid/nexus]$ nats pub gm gm
04:19:55 Published 2 bytes to "gm"

[nix-shell:~/plurigrid/nexus]$ nats pub gm gm
04:20:25 Published 2 bytes to "gm"

[nix-shell:~/plurigrid/nexus]$ nats sub -s <REDACTED IP> gm
04:22:54 Subscribing on gm
[#1] Received on "gm"
gm

[#2] Received on "gm"
gn
```
Test procedure:

Published messages to the "gm" subject using the NATS nats pub command. Subscribed to same subject from a NATS server at <REDACTED IP> using nats sub.
Received two messages on subscription, both sent by another system:
gm gn
Demonstrates publish-subscribe model for asynchronous communication between distributed, loosely coupled components. Using NATS, a lightweight cloud-native messaging system, I published and subscribed to subjects by command line.
The two message received confirm my publishes were received by NATS server, and subscription connected my nexus to the NATS cluster where another system also publishing and subscribing.

**Review by bmorphism — APPROVED** [review]
lgtm

**Pull request merged**
